# Generated by Django 4.1.1 on 2022-10-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='comment',
            new_name='content',
        ),
    ]
