# Generated by Django 4.1.1 on 2022-10-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_comment_info_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='content',
        ),
        migrations.RemoveField(
            model_name='info',
            name='date',
        ),
    ]
