# Generated by Django 4.1.1 on 2022-10-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_info_content_remove_info_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='info',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
