# Generated by Django 4.1.1 on 2022-10-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_info_content_info_date_info_e_mail_info_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='nome',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
