# Generated by Django 4.1.1 on 2022-10-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_info_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
